### ISSUE TITLE
scaleio 404 error from volume ls

### ISSUE THREAD

**Issue by garrettux** [codedellemc/libstorage#393]
Hello, we recently upgraded our scaleio cluster from 2.0 to 2.0.1 and are now getting 404 errors from rexray when attempting volume operations.

```
# rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.6.4
OsArch: Linux-x86_64
Branch: v0.6.4
Commit: aadb689a00b9fc1220baacb5042c5155fbbadb7e
Formed: Fri, 06 Jan 2017 00:07:27 GMT

libStorage
----------
SemVer: 0.3.8
OsArch: Linux-x86_64
Branch: v0.6.4
Commit: e46cfc3effe8762c8ea96107ec64f15abfe95135
Formed: Fri, 06 Jan 2017 00:07:10 GMT
```

```
# cat /etc/rexray/config.yml
libstorage:
  server:
    services:
      scaleio:
        driver: scaleio
        scaleio:
            endpoint:             https://our.cluster.url/api
            #apiVersion:           "2.0.1"
            insecure:             true
            useCerts:             true
            userName:             XXXX
            password:             XXXX
            systemID:             XXXX
            protectionDomainName: XXXX
            storagePoolName:      XXXX
            thinOrThick:          ThinProvisioned
```

grabbed the http request from strace:
```
[pid 42185] write(5, "GET /volumes/?attachments=1 HTTP/1.1\r\nHost: libstorage-server\r\nUser-Agent: Go-http-client/1.1\r\nLibstorage-Localdevices: scaleio=\r\nLibstorage-Tx: txID=40414547-53a3-48c0-72c8-f53ae70034c6, txCR=1484842663\r\nAccept-Encoding: gzip\r\n\r\n", 230) = 230
```

**Comment by cduchesne** [comment]
Did you upgrade your scaleio gateway? Last I checked, scaleio-gateway 2.0.0 is not compatible with ScaleIO 2.0.1.

**Comment by cduchesne** [comment]
Best thing to check is
```
curl -sk -u <scaleio_user>:<scaleio_password> https://<scaleio_gateway>/api/login
```
and make sure you get an auth token back. You may get an error stating incompatibility with ScaleIO MDM or some other error message. A success should result in a token response.

**Comment by garrettux** [comment]
thanks for the info.  yes, auth works with curl, and we can get the 404 via curl as well.

```
# curl -sk -u USER:PASS https://wdc04is-scioc5sds01.adm01.com/api/login
"SOMETOKEN"

# curl -sk -u USER:TOKEN https://wdc04is-scioc5sds01.adm01.com/api/version
"2.0.1"

# curl -sk -u USER:TOKEN https://wdc04is-scioc5sds01.adm01.com/api/volumes/?attachments
{
  "message" : "Not Found",
  "httpStatusCode" : 404,
  "errorCode" : 0
}
```

**Comment by akutz** [comment]
Hi @garrettux,

Can you please update your libStorage server config like so:

```yaml
libstorage:
  logging:
    level: debug
    httpRequests: true
    httpResponses: true
  server:
    services:
      scaleio:
        driver: scaleio
        scaleio:
            endpoint:             https://our.cluster.url/api
            #apiVersion:           "2.0.1"
            insecure:             true
            useCerts:             true
            userName:             XXXX
            password:             XXXX
            systemID:             XXXX
            protectionDomainName: XXXX
            storagePoolName:      XXXX
            thinOrThick:          ThinProvisioned
```

Note the additional logging information at the top of the config. Once you reproduce the issue, please post the debug log into a [gist](http://gist.github.com) and link it here. Thank you.

**Comment by garrettux** [comment]
@akutz thanks for your help.  here's the gist: https://gist.github.com/garrettux/a5b0ef536801227d2539a7cc0d675e9d

**Comment by akutz** [comment]
Hi @garrettux,

What is invoking the `GET https://<GATEWAY>/api/volumes/?attachments` [here](https://gist.github.com/garrettux/a5b0ef536801227d2539a7cc0d675e9d#file-rexray-log-L121) in the log? Are you doing the manually via curl?

**Comment by garrettux** [comment]
no, this is just the output from `rexray volume ls -l debug` after updating `/etc/rexray/config.yml` with the libstorage logging settings.

**Comment by akutz** [comment]
Would you please do me a favor, once the libStorage server is running, can you curl `/volumes?attachments=1` without the `/` after `/volumes`?

Also, to fix the issue you're seeing, update your config to look like this:

```yaml
libstorage:
  logging:
    level: debug
    httpRequests: true
    httpResponses: true
  service: scaleio
scaleio:
  endpoint:             https://our.cluster.url/api
  #apiVersion:           "2.0.1"
  insecure:             true
  useCerts:             true
  userName:             XXXX
  password:             XXXX
  systemID:             XXXX
  protectionDomainName: XXXX
  storagePoolName:      XXXX
  thinOrThick:          ThinProvisioned
```

When you just have a single service, you can shortcut the server definition with the property `libstorage.service`. This also tells REX-Ray which service to access. Take this command:

```shell
rexray volume ls -l debug
```

It results in the API call `GET /volumes/?attachments=1`, and I think there's a bug with that trailing slash after `/volumes`. However, if you do `rexray volume ls -l debug --service scaleio` then it will tell REX-Ray to make the API call `GET /volumes/scaleio?attachments=1`. Additionally, the config I posted above will also tell REX-Ray to do the same thing (in addition to being a short-cut method of defining a single service).

```
