### ISSUE TITLE
Change EFS Plugin to prioritize security group from plugin config over instance meta-data

### ISSUE THREAD

**Issue by febbraro** [codedellemc/libstorage#511]
# Summary
When installing the EFS plugin you can configure a security group using the EFS_SECURITYGROUPS variable. Use this configuration as higher priority than the security group(s) provided by the instance.

# New Feature
If the instance has only one security group, it will use that instance group by default. If it used config as higher priority, it could alert the user is they have not assigned the security group to the instance.

## Steps To Reproduce
A way to see this...

* Create SecurityGroup1 (with no NFS Port config)
* Create SecurityGroup2 (with NFS port config)
* Create an instance and assign it SecurityGroup1 (and don't assign it SecurityGroup2)
* Install the rexray/efs plugin and configure EFS_SECURITYGROUPS with SecurityGroup2
    * `docker plugin install rexray/efs EFS_SECURITYGROUPS="sg-XXXXXX"`
* Launch a docker stack with a rexray/efs volume mounted to an instance
* When the EFS Mount point is created it will have SecurityGroup1 assigned to it.

Here is a compose file that can be used via `docker stack deploy`

```yaml
version: '3.2'

services:
  test:
    image: alpine
    volumes:
      - files:/var/test/files

volumes:
  files:
    driver: rexray/efs
    driver_opts:
      size: 10
```
